---
title: "Dal Rae Project"
author: "Landon Smith"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Import and Clean Data
```{r}
#Import Pricing and Quantiity Sold CSV
dr_pricing_and_quantity_sold = read.csv("/Users/landonsmith/Desktop/Dal Rae CSVs/pricing_and_quantity_sold_food_only_1-01-2022_to_4-47-2023.csv")
dr_pricing_and_quantity_sold

#Drop Unessesary Columns
dr_pricing_and_quantity_sold = subset(dr_pricing_and_quantity_sold, select = -c(Cost, Profit, Food.Cost.Percentage))
dr_pricing_and_quantity_sold

#Change Columns from Character Datatype to Numeric
dr_pricing_and_quantity_sold$Num.Sold = as.numeric(dr_pricing_and_quantity_sold$Num.Sold)
dr_pricing_and_quantity_sold$Price.Sold = as.numeric(dr_pricing_and_quantity_sold$Price.Sold)

```

```{r}
#Categorize Into Food Groups Using ChatGPT
item_name_grouped = dr_pricing_and_quantity_sold %>% group_by(Item.Name)
item_name_grouped
```

```{r}
#Determine Most Popular Dishes in Each Price Tier (Used as Proxy in Survey)

library(dplyr)

#Compute Number Sold and Average Price by Item Name 
item_num_grouped = dr_pricing_and_quantity_sold %>% group_by(Item.Num,Item.Name) %>% summarise(number_sold = sum(Num.Sold), average_price = mean(Price.Sold))
item_num_grouped

#Classify Items by Price Tier
item_num_grouped$price_tier = ifelse(item_num_grouped$average_price > 0 & item_num_grouped$average_price <= 20, "Ultra Low", "None")
item_num_grouped$price_tier = ifelse(item_num_grouped$average_price > 20 & item_num_grouped$average_price <= 30, "Low", item_num_grouped$price_tier)
item_num_grouped$price_tier = ifelse(item_num_grouped$average_price > 30 & item_num_grouped$average_price <= 50, "Medium", item_num_grouped$price_tier)
item_num_grouped$price_tier = ifelse(item_num_grouped$average_price > 50, "High", item_num_grouped$price_tier)

item_num_grouped

#Highest Quantity Sold by Price Tier (Most Popular Dish)
low = item_num_grouped[item_num_grouped$price_tier == "Low",]
ordered_low = low[order(low$number_sold, decreasing = TRUE),]
ordered_low # The most popular steak in the low category is the Poor Man's Pepper Steak

medium = item_num_grouped[item_num_grouped$price_tier == "Medium",]
ordered_medium = medium[order(medium$number_sold, decreasing = TRUE),]
ordered_medium # The most popular steak in the medium category is the 10 oz Prime, (is this Filet?) 8 oz Filet is winner if unable to figure out 

high = item_num_grouped[item_num_grouped$price_tier == "High",]
ordered_high = high[order(high$number_sold, decreasing = TRUE),]
ordered_high # The most popular steak in the high category is the 12oz Filet Pepper Steak
```

# Create Demand Curves (Use Survey Data)
```{r}
percentages = c(0.7, 0.8, 0.9, 0.95, 1.05, 1.1, 1.2, 1.3)
price = rep(69.5, times = 8)
percentages * price
```

# Create Demand Curves (Use POS Data)
```{r}
#10 oz Filet
pricepoints = c(42,44,46,48,58)
fictional_num_of_days_at_pricepoint = c(200,210,200,500,700)
num_sold_at_pricepoint = c(833,1765,809,308,387)

#c(90,210,120,30,30)
sold_per_day = num_sold_at_pricepoint/fictional_num_of_days_at_pricepoint

sold_per_day_at_pricepoints = data.frame(pricepoints,sold_per_day)
sold_per_day_at_pricepoints

lm_model = lm(sold_per_day ~ pricepoints, data=sold_per_day_at_pricepoints)
summary(lm_model)
plot(lm_model)

library("ggplot2")
ggplot(data = sold_per_day_at_pricepoints, aes(x = sold_per_day, y = pricepoints)) +
geom_point() + geom_smooth(method = "lm") +
xlab("Sold Per Day") +
ylab("Price Points") +
ggtitle("Medium Price Category: Proxy 10oz Filet Mignon")

#Positive Relationship shouldn't exist, sample size is too small (time period)
# Dal Rae should continue to pass along its increased costs in the form of price increases based off of this graph. However, we do not expect this demand curve based on real data to continue in this trajectory as the menu price continues to increase. At some point, customers opposition to increased prices will be reflected in the true demand curve. 
```